# Generated by Django 4.2.1 on 2023-05-06 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_microphone', models.BooleanField(default=False)),
                ('can_indicator', models.BooleanField(default=False)),
                ('can_sound', models.BooleanField(default=False)),
                ('can_field_service_director', models.BooleanField(default=False)),
                ('can_read_watchtower', models.BooleanField(default=False)),
                ('can_meeting_director', models.BooleanField(default=False)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='volunteers.volunteer')),
            ],
        ),
    ]
