# Generated by Django 4.2.1 on 2023-05-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_rename_jobs_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='name',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(default='Caio', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(default='do Prado Gralho', max_length=100),
            preserve_default=False,
        ),
    ]
