# Generated by Django 4.2.1 on 2023-05-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_remove_volunteer_name_volunteer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
