# Generated by Django 4.2.1 on 2023-05-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_alter_volunteer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='can_field_service_director',
        ),
        migrations.AddField(
            model_name='job',
            name='can_field_service_conductor',
            field=models.BooleanField(default=False, verbose_name='Field Service Conductor'),
        ),
        migrations.AlterField(
            model_name='job',
            name='can_indicator',
            field=models.BooleanField(default=False, verbose_name='Indicator'),
        ),
        migrations.AlterField(
            model_name='job',
            name='can_meeting_director',
            field=models.BooleanField(default=False, verbose_name='Meeting Director '),
        ),
        migrations.AlterField(
            model_name='job',
            name='can_microphone',
            field=models.BooleanField(default=False, verbose_name='Microphone'),
        ),
        migrations.AlterField(
            model_name='job',
            name='can_read_watchtower',
            field=models.BooleanField(default=False, verbose_name='Watchtower Reader'),
        ),
        migrations.AlterField(
            model_name='job',
            name='can_sound',
            field=models.BooleanField(default=False, verbose_name='Sound'),
        ),
    ]
