# Generated by Django 4.2.1 on 2023-05-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_remove_job_can_field_service_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='can_meeting_director',
            field=models.BooleanField(default=False, verbose_name='Meeting Director'),
        ),
    ]
