# Generated by Django 4.2.1 on 2023-05-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0007_remove_job_can_meeting_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
