# Generated by Django 4.2.1 on 2023-05-06 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0008_volunteer_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='volunteers.volunteer', unique=True),
        ),
    ]
