# Generated by Django 4.2.1 on 2023-05-12 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0011_rename_volunteer_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
    ]
