# Generated by Django 4.2.1 on 2023-05-12 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0012_alter_person_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='alias',
            new_name='name',
        )
    ]
