# Generated by Django 4.2.1 on 2023-05-12 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteers', '0012_alter_person_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('assignment', models.CharField(choices=[('ML', 'Microphone Direito'), ('MR', 'Microphone Esquerdo'), ('ID', 'Indicador'), ('SV', 'Som e Vídeo'), ('FC', 'Dirigente de Campo'), ('RW', 'Leitor de Sentinela'), ('MC', 'Presidente')], max_length=2)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='volunteers.person')),
            ],
        ),
    ]
