# Generated by Django 4.2.1 on 2023-05-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_rename_excepction_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(1, 'Visita do Superintendente'), (2, 'Congresso'), (3, 'Assembleia'), (4, 'Celebração')]),
        ),
    ]
