# Generated by Django 4.2.1 on 2023-05-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_alter_assignment_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment',
            field=models.CharField(choices=[('ML', 'Microphone Direito'), ('MR', 'Microphone Esquerdo'), ('IA', 'Indicador Auditório'), ('IE', 'Indicador Entrada'), ('AV', 'Áudio e Vídeo'), ('FC', 'Dirigente de Campo'), ('RW', 'Leitor de Sentinela'), ('MC', 'Presidente')], max_length=2),
        ),
    ]
