# Generated by Django 4.2.1 on 2023-08-29 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_alter_assignment_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='date_start',
        ),
        migrations.AddField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=datetime.date(2023, 8, 29)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment',
            field=models.CharField(choices=[('ML', 'Microfone Direito'), ('MR', 'Microfone Esquerdo'), ('IA', 'Indicador Auditório'), ('IE', 'Indicador Entrada'), ('IP', 'Indicador Estacionamento'), ('AV', 'Áudio e Vídeo'), ('FC', 'Dirigente de Campo'), ('RW', 'Leitor de Sentinela'), ('MC', 'Presidente')], max_length=2),
        ),
    ]
